### ISSUE TITLE
Deleted account still visible

### ISSUE THREAD

**Issue by yurizhykin** [mycelium-com/wallet#295] opened 2016-08-31 22:11 UTC
Not sure if this is an intended behaviour or not, but when account with no transaction history is deleted, only its label dissapears and it is still present as "Contains one private key." When account has no transaction history, there is no mention of it on the blockchain, so the generated priv/pub keys can be deleted safely. Noted in app version 2.8.4.

**Comment by Giszmo** [comment] 2016-08-31 22:31
Would you have steps to reproduce this? HD accounts can't be deleted. Only archived. I assume you are talking about random single address accounts? I just created one and deleted it again and it went away just fine.

**Comment by yurizhykin** [comment] 2016-08-31 22:43
I already had 2 HD accounts, both non-empty, and created third one, with nothing on it, of course. Then I selected it, pressed "Delete" in menu, and that just deleted its label but left the account row itself that says "Contains one private key." I think  HD account can only be deleted if it has no transaction history (the "Delete" option is not available for my other accounts), but in this particular case the account was empty and it didn't work out.

**Comment by Giszmo** [comment] 2016-09-10 03:56
I tried again and can't reproduce with HD accounts neither. I would tend to close this if it doesn't result in crashes when you then try to use the account later on, as HD accounts factually can't be deleted without deleting the master seed aka the whole wallet.

**Comment by yurizhykin** [comment] 2016-09-10 11:11
Yes, sure. I think it doesn't affect security of the wallet as that key can be generated any time anyway. So close.

**Closed** 2016-09-10 11:11 UTC
Labels: bug, can't reproduce
