### ISSUE TITLE
Import a HD Account by typing the master seed words

### ISSUE THREAD

**Issue by ikilled** [mycelium-com/wallet#247] opened 2016-02-06 16:19 UTC
I would like to see the ability to **import** an HD Account by entering the 12 master seed words with keyboard (- the same way as is done for "Cold Storage Spending" feature) and not just by using scan QR code.

**Comment by Giszmo** [comment] 2016-02-07 02:45
Do you want to manage multiple separate HD wallets? If so, it's a duplicate of #203

**Closed by Giszmo** 2016-02-07 02:45 UTC
Labels: duplicate, enhancement

**Comment by ikilled** [comment] 2016-02-07 11:05
Oh, I see now...
Yes.

I thought Mycelium already implemented multiple HD ~~Accounts~~ Wallets - each with different master seed.
So when I see the multiple HD Accounts in Mycelium - they are all actually from the same master seed! :-(
