### ISSUE TITLE
Local Trader: Notification never arrives v2.3.1

### ISSUE THREAD

**Issue by ondra-novak** [mycelium-com/wallet#166] opened 2015-04-24 12:14 UTC
I saw no notification from the local trader on any device that i used or using now. Never! This doesn't work and i don't believe that it ever worked. Currently, Android 4.0.1, Mycelium v2.3.1 Missed four trades.

Only solution for now is to Disable Local Trader

**Comment by raedah** [comment] 2015-12-15 04:01
This is a duplicate of https://github.com/mycelium-com/wallet/issues/77

**Comment by DanielWeigl** [comment] 2015-12-15 08:06
see here: https://github.com/mycelium-com/wallet/issues/77#issuecomment-164679245

**Closed by DanielWeigl** 2015-12-15 08:06 UTC
