### ISSUE TITLE
Mycelium cannot detect if Orbot is already running and connected

### ISSUE THREAD

**Issue by sjug** [mycelium-com/wallet#288] opened 2016-08-09 13:29 UTC
You guys had replied to my review in the app store, but I think this is more helpful.
1. Lauch Orbot and connect to Tor.
2. Launch Mycelium.
3. Receive prompt from Mycelium asking to "Start Orbot? Orbot doesn't appear to be running. Would you like to start it up and connect to Tor? Y/N"

This is on the latest developer preview of Android N on Nexus 6P.

**Comment by DanielWeigl** [comment] 2016-08-09 13:51
Hello,

just tried it on my phone (Nexus 5) and also in an Emulator set to Nexus 6P and it works in both cases.

can you verify which orbot version you have (in orbot, menu, about) is it 15.1.2? Otherwise try to download it from here: https://guardianproject.info/releases/Orbot-v15.1.2.apk

Hmm.. just checked https://github.com/guardianproject/NetCipher/commit/f35c5fc3c2b91c1722a9d68bf9ce8d8192e1ee31 (which we use to check if orbot is running) - they made some changes how the lib finds the path of orbot.

Do you maybe have a non-default path? (eg. on external SD card, multi user, rooted...)?

Will import the changes and include them in the  next release.

**Comment by sjug** [comment] 2016-08-09 14:14
Thanks for the quick reply @DanielWeigl,

I'm running a factory fresh NPD90G build, no root, no custom anything at all.
I do have the latest available Orbot version which is 15.1.2 as you listed.
Running v2.8.4 of mycelium as well.

**Comment by DanielWeigl** [comment] 2016-08-09 16:51
Can you test this build: https://wallet.mycelium.com/download/testing/mbw-prodnet-release-2.8.4build28406.apk - i have included the upstream changes from NetCipher but im unable to test it, bec. I can not reproduce it locally

**Comment by sjug** [comment] 2016-08-09 17:37
Doesn't seem to make any difference in that build unfortunately.
Did you want a netcat or something else that could help from myside?

**Comment by DanielWeigl** [comment] 2016-08-09 17:42
Do you have adb installed on your machine? https://developer.android.com/studio/command-line/adb.html 

if so, connect your phone, start `adb shell` and enter `ps  | grep torpro` on the android shell (while orbot is running) and post the result

On my phone: 

```
shell@hammerhead:/ $ ps | grep torpro                                          
u0_a173   6807  1439  941304 88668 sys_epoll_ 00000000 S org.torproject.android
u0_a173   7089  1     2956   1044  poll_sched 00000000 S /data/data/org.torproject.android/app_bin/polipo
u0_a173   29463 1     20360  14740 sys_epoll_ 00000000 S /data/data/org.torproject.android/app_bin/tor
```

Thank you

**Comment by Giszmo** [comment] 2016-08-30 14:09
Waiting for input from @sjug since almost a month. Closing next.

**Comment by sjug** [comment] 2016-08-30 14:41
Sorry @Giszmo, will try and get the logcat info tonight.

**Comment by Giszmo** [comment] 2016-09-10 03:57
another 11 days later. closing. let us know if it's not fixed, so we can re-open it.

**Comment by sjug** [comment] 2016-09-10 15:37
Here's the output on my phone:

`angler:/ $ ps | grep torpro
u0_a106   9395  548   1111908 97276 SyS_epoll_ 0000000000 S org.torproject.android
u0_a106   9496  1     28160  22376 SyS_epoll_ 0000000000 S /data/data/org.torproject.android/app_bin/tor
u0_a106   9500  1     3832   1180  poll_sched 0000000000 S /data/data/org.torproject.android/app_bin/polipo
`

**Comment by jonathancross** [comment] 2016-10-24 12:22
> ps | grep torpro on the android shell (while orbot is running) and post the result

Hi @DanielWeigl does the output from @sjug provide what you need to debug?  I've also seen this issue a few times.

**Comment by DanielWeigl** [comment] 2016-10-24 12:29
@jonathancross, no not really - it shows that the process is running and in the folder we expect it to be

    /data/data/org.torproject.android/app_bin/tor

But for some reasons the [check](https://github.com/mycelium-com/wallet/blob/3043a0eee87a359042cb51d58ebe17624f4159f5/public/mbw/src/main/java/info/guardianproject/onionkit/ui/TorServiceUtils.java#L94) fails to find it running.

>  I've also seen this issue a few times.
On one device? or on different devices? So far we only know that if it fails, it will always fail the same way.

Can you checl if your `ps | grep` looks the same? And would you (or @sjug ) be willing to try to run the wallet in debug mode and check around the linked line above why it fails

**Comment by sjug** [comment] 2016-10-24 12:36
@DanielWeigl Yeah I can give it a try just need. You mean like import the source into android studio and run the app via debug?

**Comment by DanielWeigl** [comment] 2016-10-24 12:38
Yes - set a breakpoint at the function linked above an see why it fails to find orbot running. This code is based on [link](https://github.com/guardianproject/NetCipher/commit/f35c5fc3c2b91c1722a9d68bf9ce8d8192e1ee31). They explain that they used different methods because depending on various vendor versions one or the other might not work. Maybe on some phones (or under certain circumstances) none of them work

**Comment by Giszmo** [comment] 2016-10-24 14:56
It's being investigated and active with at least two experiencing the issue. Guess re-opening is appropriate.

**Comment by jonathancross** [comment] 2016-10-24 19:46
>> I've also seen this issue a few times.

> On one device?

Sorry, just on one device 2 or 3 times in the last couple months (Nexus 5, Android 6.0.1).

> Can you check if your ps | grep looks the same?

I've never used adb, so I'll have to learn a bit about that.

**Comment by sjug** [comment] 2016-10-29 14:10
Alright, so I've been debugging the `findProcessId` that @DanielWeigl suggested.

The strings that are set as part of this function are fine:
```
dataPath = /data/user/0
execPath = /org.torproject.android/app_bin/tor
command = /data/user/0/org.torproject.android/app_bin/tor
defaultCommand = /data/data/org.torproject.android/app_bin/tor
```

The first call to `findProcessIdCmd(command)` clearly doesn't return the `procId` because we already know from our manual ps that it's running under `defaultCommand`.
The second call `findProcessIdCmd(defaultCommand)` is what we would expect to return the correct `procId`.

However, the `findProcessIdWithPidOf(command)` inside `findProcessIdCmd` fails because `procPs` is set to some exited pid which has no `.getInputStream` so the `reader.readLine()` is still null and we don't enter that while loop.

Since `procId` is still -1 we get into the next if that calls `findProcessIdWithPS(command)` same thing essentially, `procPs` finds some other (different) `procPs` that has also existed but with `exitcode=0`. So `reader.readLine()` is not null so we enter the while loop, however the `line.indexOf` can't match so once again `procId` is still not set to anything valid. For the `reader` it only has 3 lines that it tries to match the `command` string. The first is the column headers from `ps` then there are two processes, one is the mycelium wallet process and the second is the `ps` process itself.

I've now tested this across all my devices. Nexus 6, Nexus 6P, Pixel XL all fully updated to Android 7 & 7.1 and none of them have ever worked even when they were on Android 6.

**Comment by DanielWeigl** [comment] 2016-10-31 10:36
Okay, thank you very much.

I googled around a bit, and it seems since Android 6.0 google has restricted apps to list all running processes, see here: https://code.google.com/p/android/issues/detail?id=205565 and here: https://github.com/jaredrummler/AndroidProcesses#android-nougat

On pre 6.0, the function `findProcessIdWithPS` sees all other processes - on 6.0 it only sees processes for the same AppId (thus you only got the three lines)

This means we currently dont have a reliable way to find if Orbot is running. Maybe Ill deactivate the popup on 6.0 phones and rely on the user to start orbot manually.

**Comment by sjug** [comment] 2016-10-31 11:36
It's too bad the resolution is to remove the check, but it's good to know that this is actually an issue. Thanks @DanielWeigl

**Comment by DanielWeigl** [comment] 2016-11-22 13:05
was removed in the latest update - will keep a watch on upstream changes and include them if possible

**Closed by DanielWeigl** 2016-11-22 13:05 UTC
Labels: bug, can't reproduce

**Comment by apetersson** [comment] 2016-11-24 18:39
i would suggest contacting @guardianproject  ( maybe Nathan@guardianproject.info)  - im sure they would be willing to add an intent that returns the orbot status to allow detection, specifically for this interaction. @eighthave @n8fr8

**Comment by sjug** [comment] 2016-11-24 18:40
Yeah I'm going to take a look at orfox when I get a chance, good idea.

**Comment by DanielWeigl** [comment] 2016-11-24 18:43
@apetersson ive added a comment to an already existing ticket for the error here: https://dev.guardianproject.info/issues/6847#change-10528

but did not made any suggestions on how to solve it.

**Comment by eighthave** [comment] 2016-11-25 10:31
Sounds like you are using custom code to handle Orbot.  Why not just use the NetCipher library?  It now supports HttpURLConnection, OkHTTP, Volley, ch.boye, and Apache HttpClient for Android.

**Comment by DanielWeigl** [comment] 2016-11-25 10:46
@eighthave, we use code from the netchiper lib, [link](https://github.com/guardianproject/NetCipher/commit/f35c5fc3c2b91c1722a9d68bf9ce8d8192e1ee31).  - would using the OkHTTP-wrapper help anything to inform the user to start orbot, if it isnt running?  If it is using the same `isOrbotRunning` function, then it would also fail (i.e. always report false, even if orbot is running and available), because the `ps` call fails to list all running processes.

**Comment by eighthave** [comment] 2016-11-25 10:59
That's the problem: by just using the code and not the library, you are
not getting updates, both for security and functionality.  NetCipher for
all HTTP APIs now requests that Orbot start in the background
automatically. The user can set Orbot to always prompt before starting
if they want, but that's no longer the default.  Apps that use
`OrbotHelper.requestStartTor()` then get a status Intent response from
Orbot, so that the requesting app can act upon that status info.

NetCipher works fine with Android 6 and 7.

**Comment by DanielWeigl** [comment] 2016-11-25 11:06
I see - just noticed that the function is already marked as deprecated - thx for the heads up, will give the  OkHTTP wrapper a try

**Comment by eighthave** [comment] 2016-11-25 11:38
Great!  Definitely contact us with any questions.  The OkHTTP support is
new, so we want feedback, bug reports, etc.  You can find us in many
places: https://guardianproject.info/contact
