### ISSUE TITLE
Import Private Key fails

### ISSUE THREAD

**Issue by vv01f** [mycelium-com/wallet#388] opened 2017-09-01 17:41 UTC
* recent Version 2.9.2 (290207)

* import of private key via scan or clipboard fails without any message after "Importing" indicator stopped

example:
* private key 5JtvyEY1xJSFB6tkmsLwDuCayQ8UKU5YGrPBFDJsE76yGXeDWa2
* generated via https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html

**Comment by Giszmo** [comment] 2017-09-01 19:51
It is highly discouraged to move private keys through the clipboard. Well, actually so far Mycelium encourages it but [this branch](https://github.com/mycelium-com/wallet/tree/removeClipboardHandlingOfPrivateKeys) is supposed to change that.

That said, yes, I can confirm that cold wallet spending from ![bla](https://user-images.githubusercontent.com/96378/29985376-1b5bc39a-8f35-11e7-95a6-4123e2a8e521.png) does but importing account does not work. Thank you for reporting.

**Comment by Giszmo** [comment] 2017-09-25 22:47
Checking if the address does hold colored coins, it gets an IoException and silently ignores it.

[This line](https://github.com/mycelium-com/wallet/blob/master/mbw/src/main/java/com/mycelium/wallet/colu/ColuManager.java#L899) throws. @itserg should have it fixed soon.

**Comment by Giszmo** [comment] 2017-09-27 03:20
fixed in master, due to be released with next release.

**Closed by Giszmo** 2017-09-27 03:20 UTC
Labels: bug
