### ISSUE TITLE
CPFP intermediary fee, 

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#365] opened 2017-06-27 23:27 UTC
Mayny people will want to use CPFP because they cheaped out on a transaction and now want it to get to normal speed.

Right now it seems like the fee bump only assume going from normal to high priority.
My transaction was at 160 sat/byte, I'm sure there is a middle ground before 460 sat.

(btw it confirmed just as I typed this.)

**Comment by Giszmo** [comment] 2017-06-28 07:22
The reason I did not provide a way to set the fee on the bumping transaction was because if you once bumped too little, you are out of luck for bumping more unless RBF is used. At least with the limited implementation it currently is. It only looks at the unconfirmed transaction and not at its parents or parallel bumping transactions, so I decided to make that one shot at RBF count.

I will work on RBF soon, at which point we can re-address this.

**Comment by Giszmo** [comment] 2017-09-11 18:32
With RBF, fee bumping will need to be addressed anyway but it will not use CPFP in the sending case. Closing for now.

**Closed by Giszmo** 2017-09-11 18:32 UTC
Labels: enhancement, mining fee
