### ISSUE TITLE
Important: Found an Mycellium open app pin bug

### ISSUE THREAD

**Issue by lichtamberg** [mycelium-com/wallet#157] opened 2015-04-09 07:55 UTC
braddoge reported the folllowing issue:

http://www.reddit.com/r/Bitcoin/comments/31yz8i/found_an_mycellium_open_app_pin_bug/

```
After using the new feature of having a pin to open the app have noticed 
sometimes on my Samsung gs4 that if you open the app and click on the 
background the pin pad goes away and then after a small period of time 
around ten seconds you can click the back button on the phone and it 
will open the wallet... it doesnt always work though. 
```

**Comment by DanielWeigl** [comment] 2015-04-09 08:29
Thank you for reporting - so far I was not able to reproduce it, but I made some changes to the PIN dialog, that it cant be closed. Will be included in the next release.

**Comment by jandreske** [comment] 2015-06-03 14:52
with the next release, it will no longer be possible to dismiss that opening PIN dialog

**Closed by jandreske** 2015-06-03 14:52 UTC
