### ISSUE TITLE
HTTP 400 error when sending payment

### ISSUE THREAD

**Issue by MiniOtacon** [mycelium-com/wallet#321] opened 2016-12-27 19:59 UTC
Here's the error message I got when attempting to send to a Coinbase address. I noticed a similar issue (#221) but that's a 403 error with BitPay and not Coinbase.

![screenshot_2016-12-27-11-50-24](https://cloud.githubusercontent.com/assets/14066723/21507178/f62ffca8-cc2a-11e6-9a53-303d8683fd68.png)

Any solutions would be appreciated. I have tried to send payment three times with same error message as a result.

**Comment by Giszmo** [comment] 2016-12-27 21:48
Thank you for reporting this. Sounds like Coinbase didn't like the request but it's hard to know if they were too picky or mycelium too sloppy about some implementation detail. We will check with them if they have logs regarding 9F3L8CZZ.

**Comment by Giszmo** [comment] 2017-01-02 14:54
Coinbase replied. The important bit is

> it may be wallet specific because we have not heard any other reports of this issue and 400 is for Bad Request which is typically due to a malformed request sent by the client. However, I’m asking our merchant dev team so we can get input from others in case they know more.
> Regarding the order itself, nothing looks out of the ordinary with the order. It’s status is expired and no payment was received. Otherwise it is a valid order.

I guess with this, we have confirmation it is no "big" issue, affecting all or most of our users. I would close this if @MiniOtacon can't reproduce it neither or doesn't reply soon.

**Comment by Giszmo** [comment] 2017-01-16 18:58
Coinbase is still at it. Already on January 10th they wrote:

> After quite a bit of testing, I was able to reproduce the 400 Bad Request error using Mycelium on Android.
> 
> I reproduced it by:
> 1. Visiting https://www.coinbase.com/checkouts/7dc893c1af011c95b91b13f24a4cdbd8 on a computer.
> 2. Clicking $0.10, scanning the QR code using Mycelium on Android, and sending payment.
> 3. An 400 error message similar to the one in your screenshot was shown.
> 
> I believe the cause is probably on the Coinbase side. We have a related issue for Coinbase orders that use a suggested amount and it was only with using Suggested Amounts on our orders that I was able to reproduce this. Fortunately, suggested amount isn’t used very often, so it’s a rather isolated error message.
> 
> I’ve updated the internal bug report for the error message with additional details about how to reproduce and with the screenshot showing the 400 error so that our merchant team can investigate and fix the underlying issue.

**Comment by Rassah** [comment] 2017-01-30 21:54
In the last two uses, I didn't have this error any more. Most recent yesterday. But I tried to make the payment go through as fast as possible, broadcasting it within a minute, so maybe it's fixed now.

**Comment by Giszmo** [comment] 2017-09-11 17:54
I assume it might be fixed. Definitely no major issue telling from what hits support.

**Closed by Giszmo** 2017-09-11 17:54 UTC
Labels: bug, can't reproduce
