### ISSUE TITLE
activity reset on rotation fix

### ISSUE THREAD

**Issue by ewhite-dev** [mycelium-com/wallet#134] opened 2014-11-21 18:05 UTC
I'm not in the google group, but there was a discussion about how BIP38 input is reset if the screen is rotated, and the devs made an excuse about how the android default behavior would require a fix and that its low priority, well thats an odd excuse and is not a general design pattern, despite android's default behavior so here is the fix

android:configChanges="orientation|keyboardHidden|screenSize"

add that in your manifest file to the activity tags

example

<activity
            android:name="package.name.MycelliumActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:label="@string/app_name" />

this tells the application when you want to handle config changes yourself and that the activity shouldn't handle it itself. This has nothing to do with saving the state of the instance, UNLESS you start running into memory problems (you won't, but let the beta testers see it themselves and you'll figure out which method has more utility)

**Comment by Giszmo** [comment] 2015-12-18 20:53
duplicate of fixed #52

**Closed by Giszmo** 2015-12-18 20:53 UTC

**Comment by Giszmo** [comment] 2015-12-18 20:54
oh :) @ewhite-dev thanks, if that was your fix
