### ISSUE TITLE
Hide CPFP option if watch-only wallet

### ISSUE THREAD

**Issue by jmliz** [mycelium-com/wallet#351] opened 2017-05-02 14:02 UTC
The wallet crashes on Android when a user tries to do CPFP fee replacement on imported watch only accounts. I did it by mistake, so I noticed. I think a little message will do. or remove the option to begin with in this case.

**Comment by Giszmo** [comment] 2017-05-03 19:10
good point. thanks. noted.

**Comment by Giszmo** [comment] 2017-09-11 18:21
this is a duplicate of #362

**Closed by Giszmo** 2017-09-11 18:21 UTC
Labels: bug, duplicate, mining fee
