### ISSUE TITLE
Loading two accounts from one backup.

### ISSUE THREAD

**Issue by jarys** [mycelium-com/wallet#320] opened 2016-12-27 11:02 UTC
I backuped and then I divided my coins into two HD accounts. When I loaded from these 12 words on the second device, only the first HD account was loaded even though the second account has not own different 12 words. What is the mistake?

**Comment by vnnkl** [comment] 2016-12-27 11:16
When restoring the wallet will not go through all accounts and check whether they have balance and automatically add them.
Simply add a new HD account on the second device and it will find that it already has a balance and add it accordingly.

**Comment by Giszmo** [comment] 2016-12-27 13:02
this is a recurring issue (and happened to me, too). Not exploring beyond the first account is in line with the Bitcoin standard (BIP44) but we should add some "Transactions found on account. Want to check the next account, too?" on adding accounts with transactions. (I would actually like a feature that would ease me the exploration of my 35 accounts in one step but that's another story.)

The only question is, should we add any change to the current wallet or should we focus on the new wallet (looking at @Rassah ).

**Comment by Giszmo** [comment] 2016-12-27 13:03
Closing as duplicate of #313

**Closed by Giszmo** 2016-12-27 13:03 UTC
