### ISSUE TITLE
Localtrader access trader's profile info from active trades and trade history

### ISSUE THREAD

**Issue by hughbragg** [mycelium-com/wallet#391] opened 2017-09-12 12:20 UTC
When a trade becomes active, parties should be able to view the other trader's profile data.
Current workaround it to back up to buy or sell bitcoin tabs and try to find the other trader's listing.
They won't always have a listing so it's difficult to know what their trade history data is or anything else useful info like Localtrader ID that might help to conclude a successful transaction.
If there was a link to the trader info from the trade, that would be very helpful.

**Comment by Giszmo** [comment] 2017-09-17 20:03
duplicate of #213

**Closed by Giszmo** 2017-09-17 20:03 UTC
Labels: duplicate, local trader
